# config.yml
#Ici sont les chemins des fichiers d'entrée et de sortie.

# chemins des fichiers d'entrée

input_paths:
  drugs: "data/input/drugs.csv"
  pubmed_csv: "data/input/pubmed.csv"
  pubmed_json: "data/input/pubmed.json"
  clinical_trials: "data/input/clinical_trials.csv"

# chemins des fichiers de sortie
output_path:
  graph: "data/output/drug_graph.json"
